name: Docker registry

on:
  push:
    branches:
      - master

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        if: success()
        run: docker build -t lawfulhacker/kube-http-echo:latest .

      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push lawfulhacker/kube-http-echo:latest
